name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Notify slack
      id: slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: ./
      with:
        channel: '@josh.larson'
        status: STARTED
        color: warning
    - name: yarn install
      run: |
        yarn
      env:
        CI: true
    - name: Notify slack success
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: ./
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: '@josh.larson'
        status: SUCCESS
        color: good
